export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const DESCRIPTION_INSTALLATION='DESCRIPTION_INSTALLATION';
export const DESCRIPTION_LIGHTING='DESCRIPTION_LIGHTING';
export const DESCRIPTION_AUTOMATION="DESCRIPTION_AUTOMATION";
export const DESCRIPTION_ENTERTEINMANT="DESCRIPTION_ENTERTEINMANT";
export const DECRITPTION_VIDEO="DECRITPTION_VIDEO";
export const DECRIPTION_ALARM='DECRIPTION_ALARM';
export const DECRITPION_NETWORKS='DECRITPION_NETWORKS';

export const FADE_EFECT='FADE_EFECT';